### ISSUE TITLE
Add a different clustering method in the Store Sales clustering notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/Hacktoberfest2022#10]
Use a dendrogram to find the optimum number of clusters and then perform Hierarchical Clustering

**Comment by aaryanshsahay** [comment]
could you assign this to me?

**Comment by Anubhav-Goyal01** [comment]
Sure @aaryanshsahay

**Comment by aaryanshsahay** [comment]
hey im done requesting a pr
