### ISSUE TITLE
Add Boxplot of all the numerical columns in Ecommerce spending notebook

### ISSUE THREAD

**Issue by Anubhav-Goyal01** [Anubhav-Goyal01/Hacktoberfest2022#4]
There are 4 features and a target column in the Ecommerce Spending dataset. Add a boxplot of all those 5 columns in the notebook.
Don't create 5 different figures, use the subplots functionality instead

**Comment by navya-Singla-1-3-0-9** [comment]
Hey, I would like to work on this! Please assign this issue to me.

**Comment by Anubhav-Goyal01** [comment]
Assigned it to you @navya-Singla-1-3-0-9
